language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - truffleruby
  - jruby
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
    - rvm: truffleruby
    - rvm: jruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  exclude:
    - rvm: 2.3
      os: osx
    - rvm: 2.4
      os: osx
    - rvm: 2.5
      os: osx
    - rvm: jruby-head
      os: osx
    - rvm: rbx-3
      os: osx
  fast_finish: true

os:
  - linux
  - osx

env:
  # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
  - LISTEN_TESTS_DEFAULT_LAG=2
