language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.2.0
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  exclude:
    - rvm: jruby
      os: osx
    - rvm: rbx-2
      os: osx
os:
  - linux
  - osx
sudo: false
