language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.2.0
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  exclude:
    - rvm: jruby
      os: osx
    - rvm: rbx-2
      os: osx
os:
  - linux
  - osx
env:
  global:
    - LISTEN_TESTS_DEFAULT_LAG=0.8 LISTEN_TESTS_DEFAULT_TCP_LAG=1.2
  matrix:
    - LISTEN_GEM_FSEVENT_NO_RECURSION=0 LISTEN_GEM_SIMULATE_FSEVENT=0
    # try without recursion on both OSX and Linux (simulated OSX)
    - LISTEN_GEM_FSEVENT_NO_RECURSION=1 LISTEN_GEM_SIMULATE_FSEVENT=1
    - LISTEN_GEM_FSEVENT_NO_RECURSION=1 LISTEN_GEM_SIMULATE_FSEVENT=1 LISTEN_TESTS_POLLING=1
sudo: false
